services:
  postgres:
    container_name: pos-scm-starter-learn
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devonly
      POSTGRES_DB: postgres
      # DATABASE_URL: "postgresql://postgres:devonly@localhost:5432/postgres?schema=public"
    volumes:
      - scm_starterkit:/var/lib/postgresql/data

volumes:
  scm_starterkit:

